export const HOME_DESIGN_WIDTH = 1440;

export const HOME_SERVICE_CARD_WIDTH = 258;
export const HOME_SERVICE_CARD_HEIGHT = 553;
export const HOME_SERVICE_CARD_RADIUS = 19;
export const HOME_SERVICE_CARD_GAP = 12;

export const HOME_SECTION_EYEBROW_SIZE = 16;
export const HOME_SECTION_TITLE_SIZE = 35;
export const HOME_HERO_BRAND_SIZE = 180;
